### ISSUE TITLE
How to include node_modules in `start-api`?

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-sam-local#127]
I understand the usual SAM process where you run `package` which packages up your code along with its dependencies, and it spits out a CloudFormation template that points to said code on an S3 bucket.

What I don't understand is how to make node packages work when testing locally using `sam local start-api`. My code bombs out because I'm trying to use functions that are `require`d, but obviously can't be found.

How do I include the contents of `node_modules` when using `start-api`? (I'm using `aws-serverless-express` to create a serverless Express backend)

**Comment by sanathkr** [comment]
Where is your node_modules with respect to the CodeUri?

Usually, if CodeUri points to a directory that contains your node_modules, it gets directly mounted in the Docker container. But if you don't have that structure, then you need some build process (gulp?) that moves code around in right structure for you. This is required anyway because Lambda cloud will expect the same structure as SAM Local.

**Comment by sanathkr** [comment]
Closing this in favor of #125
