### ISSUE TITLE
Debug the Lambda function on AWS-SAM-LOCAL in Eclipse

### ISSUE THREAD

**Issue by addictedanshul** [awslabs/aws-sam-local#237]
Followed below steps:

1. In the Eclipse Project Explorer, open HelloWorldHandler.java.
2. Right-click in your Eclipse code window, choose Debug As, and then choose AWS SAM Local.
3. For this example, leave the Project and Template as they are.
4. Choose Lambda Function in the Run as field.
5. Choose GetHelloWorld in the Function identifier field.
6. For this example, we will provide an Amazon S3 event. Choose Generate next to the Event input box.
7. Choose a region that has your Amazon S3 bucket.
8. Enter a valid Amazon S3 bucket name.
9. Enter a valid Amazon S3 object key, and then choose OK.
10. On the Save As page, select the current project and enter a name for the event file. In this example, we used s3-event.json.
11. Choose OK to save the event file and get back to the main dialog box.
12. Leave the advanced settings as they are. See Advanced Settings to learn more about those fields.
13. Choose Apply, and then choose Debug.

14. Had also created docker connection in Eclipse Docker Explorer, which connects successfully

-------------------------------------------------------------------------------------------------------------

Eclipse lambda project not able to connect to docker image on my windows system
lambci/lambda:java8

Got below error in eclipse:

[AWS Toolkit] Running command: C:\Users\XXXXXXX\AppData\Roaming\npm\sam.exe local invoke ExampleFunction --debug-port 5858 --event D:\Projects\lambda-worker\src\test\resources\s3-event.put.json --profile default --template D:\Projects\lambda-worker\.serverless.template
[AWS Toolkit] Waiting for SAM Local to attach the port 5858
2017/12/22 15:35:56 Successfully parsed D:\Projects\lambda-worker\.serverless.template
2017/12/22 15:35:56 Running AWS SAM projects locally requires Docker. Have you got it installed?
2017/12/22 15:35:56 error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[AWS Toolkit] SAM Local invocation done.

**Comment by danielmiralles** [comment]
The cause of this issue is  some environment variables that are not configured. First check the following list:

1. You are running the default docker machine
Open the Quick Start Console and type 'docker-machine ls' and you see the default machine Running.

2. The docker binary are in Path. 
Open Environment Variables configuration Windows, edit Path and you see the installation path of docker (in my case C:\Program Files\Docker Toolbox)

3. The docker env variables are properly configured. 
Type 'docker-machine env --shell cmd default' and see the output. Ensure that you have configured all variables (the lines begin with 'SET' in the output) in User Environment Variables.

4. Configure HOME env Variable (referred to another SAM issue).
Check that you have configured HOME environment variable in User Environment Variables pointing to your user home (C:\Users\<username>).

This work for me, connot debug (...yet) but i can run. Good Luck...

**Comment by addictedanshul** [comment]
Instead of using Docker toolbox, I started Docker daemon using Docker community edition. This time instead of using VirtualBox which is inherently used by Docker toolbox, I used hyper-V for virtualization. And it worked.

**Comment by vinayak-kaviskar** [comment]
i am facing the same issue in ubunto 18-04, can anybody help please?
