### ISSUE TITLE
Failing to remote debug Python Lambda using pydevd

### ISSUE THREAD

**Issue by MCLDG** [awslabs/aws-sam-local#54]
I've tried various combinations to get remote debugging to work, but so far I'm unsuccessful. In my environment I'm using a Mac with PyDev IDE. I start the PyDev debug server on port 5678. I can run a local Python script from the command line using pydevd and it connects to my debug server, and I'm able to remotely debug the code.

With 'sam local', I use the simple Lambda below, but it does not connect to my debug server in PyDev: 

```
import pydevd

print('Loading function')

def handler(event, context):
    pydevd.settrace("0.0.0.0", port=5678)
    message = event['Records'][0]['Sns']['Message']
    print("From SNS: " + message)
```
Here is the output:

```
$ sam local invoke AirmileFunction --debug-port 5678 --template sam-airmile-with-stack-dependency.yml --event testSNSEvent.json 
2017/08/16 11:13:42 0.1.0
2017/08/16 11:13:42 Successfully parsed sam-airmile-with-stack-dependency.yml (version 2010-09-09)
2017/08/16 11:13:42 Connected to Docker 1.27
2017/08/16 11:13:42 Fetching lambci/lambda:python2.7 image for python2.7 runtime...
python2.7: Pulling from lambci/lambda
Digest: sha256:6df7061392bd2fe09b6422b24a821f4a98c799b071d5a080989e9dda8ce3ffe7
Status: Image is up to date for lambci/lambda:python2.7
2017/08/16 11:13:46 Invoking calc-airmile-lambda.handler (python2.7)
START RequestId: 602c0719-e605-4544-8307-275f2159d54a Version: $LATEST
warning: Debugger speedups using cython not found. Run '"/usr/bin/python2.7" "/var/task/setup_cython.py" build_ext --inplace' to build.
Loading function
Could not connect to 0.0.0.0: 5678
Traceback (most recent call last):
  File "/var/task/_pydevd_bundle/pydevd_comm.py", line 524, in start_client
    s.connect((host, port))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

If I run the PyDev debug server first, I see the following error, so I run 'sam local' first, then start the debug server. The usual approach is to start the debug server first, then run the python script that connects to the debug server:

`Bind for 0.0.0.0:5678 failed: port is already allocated`

**Comment by PaulMaddox** [comment]
Hi @MCLDG,

In most debugging scenarios, the process inside the container will host the debug server, and the IDE will connect to that. This is how Node.JS, Java and remote-pdb for Python work.

It seems PyDev is the other way around; you're starting a debug server on your machine and want the Lambda script to connect out to it.

To do this, don't specify the `-d` or `--debug-port` options to SAM Local (these map through the port on your machine, into the container - which is why you're seeing the port already allocated message).

Instead, just specify the IP address of your main machine in the `pyd.settrace()` method. For example, if your laptop IP address was 192.168.0.1, you would put `pydevd.settrace("192.168.0.1", port=5678)`.

Feel free to reopen this issue if that doesn't resolve the problem for you.

**Comment by neuberfran** [comment]
Hi,

pls help me
I stay trying this:  https://cuprak.info/2017/10/09/debugging-aws-lambda-with-netbeans/amp/ 

and I'm having similar problems

https://drive.google.com/file/d/0B9gPdWq4OH-XTThHMktHYzlGWjg/view?usp=sharing

https://drive.google.com/file/d/0B9gPdWq4OH-XTThHMktHYzlGWjg/view?usp=sharing
